// Code generated by "stringer -type=Code"; DO NOT EDIT

package errors

import "fmt"

const (
	_Code_name_0 = "bad_requestunauthorizeddelinquentforbiddennot_found"
	_Code_name_1 = "not_acceptable"
	_Code_name_2 = "invalid_params"
	_Code_name_3 = "rate_limit"
	_Code_name_4 = "internal_server"
)

var (
	_Code_index_0 = [...]uint8{0, 11, 23, 33, 42, 51}
	_Code_index_1 = [...]uint8{0, 14}
	_Code_index_2 = [...]uint8{0, 14}
	_Code_index_3 = [...]uint8{0, 10}
	_Code_index_4 = [...]uint8{0, 15}
)

func (i Code) String() string {
	switch {
	case 400 <= i && i <= 404:
		i -= 400
		return _Code_name_0[_Code_index_0[i]:_Code_index_0[i+1]]
	case i == 406:
		return _Code_name_1
	case i == 422:
		return _Code_name_2
	case i == 429:
		return _Code_name_3
	case i == 500:
		return _Code_name_4
	default:
		return fmt.Sprintf("Code(%d)", i)
	}
}
